<?php

return [
    'rates' => [
        'AT' => [
            'country' => 'Austria',
            'vat_name' => 'Umsatzsteuer',
            'vat_abbr' => 'USt',
            'standard_rate' => 20,
            'reduced_rate' => 10,
            'reduced_rate_alt' => 13,
            'super_reduced_rate' => false,
            'parking_rate' => 12,
        ],
        'BE' => [
            'country' => 'Belgium',
            'vat_name' => 'Taxe sur la valeur ajoutée',
            'vat_abbr' => 'TVA/BTW',
            'standard_rate' => 21,
            'reduced_rate' => 12,
            'reduced_rate_alt' => 6,
            'super_reduced_rate' => false,
            'parking_rate' => 12,
        ],
        'BG' => [
            'country' => 'Bulgaria',
            'vat_name' => 'Dana Dobavena Stoynost',
            'vat_abbr' => 'DDS',
            'standard_rate' => 20,
            'reduced_rate' => 9,
            'reduced_rate_alt' => false,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'CY' => [
            'country' => 'Cyprus',
            'vat_name' => 'Foros prostithemenis axias',
            'vat_abbr' => 'FPA',
            'standard_rate' => 19,
            'reduced_rate' => 9,
            'reduced_rate_alt' => 5,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'CZ' => [
            'country' => 'Czech Republic',
            'vat_name' => 'Dani z pridane hotnoty',
            'vat_abbr' => 'DPH',
            'standard_rate' => 21,
            'reduced_rate' => 15,
            'reduced_rate_alt' => 10,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'DK' => [
            'country' => 'Denmark',
            'vat_name' => 'Omsaetningsavgift',
            'vat_abbr' => 'MOMS',
            'standard_rate' => 25,
            'reduced_rate' => false,
            'reduced_rate_alt' => false,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'DE' => [
            'country' => 'Germany',
            'vat_name' => 'Umsatzsteuer',
            'vat_abbr' => 'USt',
            'standard_rate' => 19,
            'reduced_rate' => 7,
            'reduced_rate_alt' => false,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'EE' => [
            'country' => 'Estonia',
            'vat_name' => 'Käibemaks',
            'vat_abbr' => 'KMKR',
            'standard_rate' => 20,
            'reduced_rate' => 9,
            'reduced_rate_alt' => false,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'GR' => [
            'country' => 'Greece',
            'vat_name' => 'Foros prostithemenis axias',
            'vat_abbr' => 'FPA',
            'standard_rate' => 24,
            'reduced_rate' => 13,
            'reduced_rate_alt' => 6,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'ES' => [
            'country' => 'Spain',
            'vat_name' => 'Impuesto sobre el valor añadido',
            'vat_abbr' => 'IVA',
            'standard_rate' => 21,
            'reduced_rate' => 10,
            'reduced_rate_alt' => false,
            'super_reduced_rate' => 4,
            'parking_rate' => false,
        ],
        'FI' => [
            'country' => 'Finland',
            'vat_name' => 'Arvonlisävero',
            'vat_abbr' => 'ALV',
            'standard_rate' => 24,
            'reduced_rate' => 14,
            'reduced_rate_alt' => 10,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'FR' => [
            'country' => 'France',
            'vat_name' => 'Taxe sur la valeur ajoutée',
            'vat_abbr' => 'TVA',
            'standard_rate' => 20,
            'reduced_rate' => 10,
            'reduced_rate_alt' => 5.5,
            'super_reduced_rate' => 2.1,
            'parking_rate' => false,
        ],
        'HR' => [
            'country' => 'Croatia',
            'vat_name' => 'Porez na dodanu vrijednost',
            'vat_abbr' => 'PDV',
            'standard_rate' => 25,
            'reduced_rate' => 13,
            'reduced_rate_alt' => 5,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'IT' => [
            'country' => 'Italy',
            'vat_name' => 'Imposta sul valore aggiunto',
            'vat_abbr' => 'IVA',
            'standard_rate' => 22,
            'reduced_rate' => 10,
            'reduced_rate_alt' => 4,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'LV' => [
            'country' => 'Latvia',
            'vat_name' => 'Pievienotas vertibas nodoklis',
            'vat_abbr' => 'PVN',
            'standard_rate' => 21,
            'reduced_rate' => 12,
            'reduced_rate_alt' => false,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'LT' => [
            'country' => 'Lithuania',
            'vat_name' => 'Pridetines vertes mokestis',
            'vat_abbr' => 'PVM',
            'standard_rate' => 21,
            'reduced_rate' => 9,
            'reduced_rate_alt' => 5,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'LU' => [
            'country' => 'Luxembourg',
            'vat_name' => 'Taxe sur la valeur ajoutée',
            'vat_abbr' => 'TVA',
            'standard_rate' => 17,
            'reduced_rate' => 14,
            'reduced_rate_alt' => 8,
            'super_reduced_rate' => 3,
            'parking_rate' => 12,
        ],
        'HU' => [
            'country' => 'Hungary',
            'vat_name' => 'Általános forgalmi adó',
            'vat_abbr' => 'AFA',
            'standard_rate' => 27,
            'reduced_rate' => 18,
            'reduced_rate_alt' => 5,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'IE' => [
            'country' => 'Ireland',
            'vat_name' => 'Value added tax',
            'vat_abbr' => 'VAT',
            'standard_rate' => 23,
            'reduced_rate' => 13.5,
            'reduced_rate_alt' => 9,
            'super_reduced_rate' => 4.8,
            'parking_rate' => 13.5,
        ],
        'MT' => [
            'country' => 'Malta',
            'vat_name' => 'Value added tax',
            'vat_abbr' => 'VAT',
            'standard_rate' => 18,
            'reduced_rate' => 7,
            'reduced_rate_alt' => 5,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'NL' => [
            'country' => 'Netherlands',
            'vat_name' => 'Omzetbelasting',
            'vat_abbr' => 'OB',
            'standard_rate' => 21,
            'reduced_rate' => 9,
            'reduced_rate_alt' => false,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'PL' => [
            'country' => 'Poland',
            'vat_name' => 'Podatek od towaròw i uslug',
            'vat_abbr' => 'VAT',
            'standard_rate' => 23,
            'reduced_rate' => 8,
            'reduced_rate_alt' => 5,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'PT' => [
            'country' => 'Portugal',
            'vat_name' => 'Imposto sobre o valor acrescentado',
            'vat_abbr' => 'IVA',
            'standard_rate' => 23,
            'reduced_rate' => 13,
            'reduced_rate_alt' => 6,
            'super_reduced_rate' => false,
            'parking_rate' => 13,
        ],
        'RO' => [
            'country' => 'Romania',
            'vat_name' => 'Taxa pe valoarea adãugata',
            'vat_abbr' => 'TVA',
            'standard_rate' => 19,
            'reduced_rate' => 9,
            'reduced_rate_alt' => 5,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'SI' => [
            'country' => 'Slovenia',
            'vat_name' => 'Davek na dodano vred nost',
            'vat_abbr' => 'DDV',
            'standard_rate' => 22,
            'reduced_rate' => 9.5,
            'reduced_rate_alt' => 5,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'SK' => [
            'country' => 'Slovakia',
            'vat_name' => 'Dan z pridanej hodnoty',
            'vat_abbr' => 'DPH',
            'standard_rate' => 20,
            'reduced_rate' => 10,
            'reduced_rate_alt' => false,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'SE' => [
            'country' => 'Sweden',
            'vat_name' => 'Mervärdeskatt',
            'vat_abbr' => 'ML',
            'standard_rate' => 25,
            'reduced_rate' => 12,
            'reduced_rate_alt' => 6,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'GB' => [
            'country' => 'Great Britain',
            'vat_name' => 'VAT and duties',
            'vat_abbr' => 'VAT',
            'standard_rate' => 20,
            'reduced_rate' => 5,
            'reduced_rate_alt' => false,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
        'SA' => [
            'country' => 'Saudi Arabia',
            'vat_name' => 'VAT',
            'vat_abbr' => 'VAT',
            'standard_rate' => 15,
            'reduced_rate' => false,
            'reduced_rate_alt' => false,
            'super_reduced_rate' => false,
            'parking_rate' => false,
        ],
    ],
];
